# Generated by Django 3.2.4 on 2021-08-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll_no', models.IntegerField()),
                ('city', models.CharField(max_length=10)),
                ('pass_by', models.CharField(default=0, max_length=10)),
            ],
        ),
    ]
